{
	"_Type": "Action.Type.ODataService.Initialize",
	"ActionResult": {
		"_Name": "init"
	},
	"OnFailure": "/MobileDemoSampleApp/Actions/Service/InitializeOfflineFailureMessage.action",
	"OnSuccess": "/MobileDemoSampleApp/Actions/LogSetState.action",
	"ShowActivityIndicator": true,
	"ActivityIndicatorText": "Downloading...",
	"Service": "/MobileDemoSampleApp/Services/SampleServiceV2.service",
	"DefiningRequests": [
		{
			"Name": "Customers",
			"Query": "Customers"
		},
		{
			"Name": "Products",
			"Query": "Products"
		},
		{
			"Name": "SalesOrderHeaders",
			"Query": "SalesOrderHeaders"
		},
		{
			"Name": "SalesOrderItems",
			"Query": "SalesOrderItems"
		}
	]
}