{
	"_Type": "Action.Type.Logger.Upload",
	"ActionResult": {
		"_Name": "LogUpload"
	},
	"OnFailure": "/MobileDemoSampleApp/Actions/LogUploadFailure.action",
	"OnSuccess": "/MobileDemoSampleApp/Actions/LogUploadSuccessful.action"
}